@echo off
REM WARNING: This file was generated from 'cottontail/ct_makeproject/templates_assets/template__assets_autobake.bat' and should not be modified.

cargo watch --watch assets --watch cottontail/ct_assetbaker --exec "run --package ct_assetbaker"