@echo off
REM WARNING: This file was generated from 'cottontail/ct_makeproject/templates_repository/template__git_push.bat' and should not be modified.

git push
git subtree push --prefix=cottontail cottontail master
