@echo off
REM WARNING: This file was generated from 'cottontail/ct_makeproject/templates_repository/template__git_merge_upstream_changes.bat' and should not be modified.

git fetch origin master
git fetch cottontail master

git pull origin master
git subtree pull --prefix=cottontail cottontail master --squash
