@echo off
REM WARNING: This file was generated from 'cottontail/ct_makeproject/templates_repository/template__git_update_cottontail.bat' and should not be modified.

git submodule update --remote && ^
pushd cottontail && ^
git fetch && ^
git checkout master && ^
git pull origin master && ^
popd

pause